backend:
  name: github
  repo: millimetr/millimetr-netlify-cms

display_url: millimetr Netlify CMS

media_folder: src/static/media
public_folder: /media

collections:
  - name: pages
    label: Pages
    folder: src/data/pages

    fields: 
      - name: title
        label: Title
        default: about
        widget: string

      - name: content
        label: Content
        widget: markdown
